### ISSUE TITLE
Server won't start

### ISSUE THREAD

**Issue by Phyroks** [mlhnono68/azuriom-egg#8]
[Hosting Network Daemon]: Checking server disk space usage, this could take a few seconds...
[Hosting Network Daemon]: Updating process configuration files...
[Hosting Network Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Hosting Network Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from mlhnono68/azuriom-egg 
Status: Image is up to date for ghcr.io/mlhnono68/azuriom-egg:v0.0.4 
Digest: sha256:0b6f8788230a7540fbda72887a80e8e942893ee7a133331c789d501c8529fe01 
[Hosting Network Daemon]: Finished pulling Docker container image
INFO: No embedded MariaDB database because no EMBEDDED_MYSQL_PASSWORD has been set
Starting PHP...
Preparing nginx.conf...
Listening to 109.230.239.169:2000
Starting nginx...
nginx: [emerg] bind() to MY.IP:2000 failed (99: Address not available)

**Comment by mlhnono68** [comment]
Logs somehow tell that the allocation is wrong and the container nginx cannot bind to it for listening to requests. I miss context of your networking but would verify you can use the same allocation (109.230.239.169:2000) with some other egg. Did you configure multiple allocations ? Maybe your network would require 0.0.0.0:2000 ?

**Comment by NoahPodcast** [comment]
Hello no response from your side for two years, I am closing the ticket
